export type Stage =
  | "Group Stage"
  | "Round of 32"
  | "Round of 16"
  | "Quarter-final"
  | "Semi-final"
  | "Third Place"
  | "Final";

export type Category = "Cat1" | "Cat2" | "Cat3" | "Cat4";

export interface PriceTier {
  category: Category;
  label: string;
  description: string;
  priceUsd: number;
}

export interface Match {
  id: string;
  stage: Stage;
  matchNo: string;
  group?: string;
  date: string; // ISO
  kickoffLocal: string; // "20:00"
  homeTeam: string;
  homeFlag: string;
  awayTeam: string;
  awayFlag: string;
  venue: string;
  city: string;
  country: string;
  prices: PriceTier[];
  featured?: boolean;
}

// FIFA-published starting prices (USD) by stage. Cat4 = lowest, Cat1 = best seat.
const PRICES: Record<Stage, Record<Category, number>> = {
  "Group Stage":   { Cat4: 60,   Cat3: 160,  Cat2: 315,  Cat1: 555 },
  "Round of 32":   { Cat4: 85,   Cat3: 205,  Cat2: 400,  Cat1: 695 },
  "Round of 16":   { Cat4: 105,  Cat3: 255,  Cat2: 495,  Cat1: 860 },
  "Quarter-final": { Cat4: 185,  Cat3: 445,  Cat2: 870,  Cat1: 1510 },
  "Semi-final":    { Cat4: 455,  Cat3: 1095, Cat2: 2135, Cat1: 3715 },
  "Third Place":   { Cat4: 295,  Cat3: 705,  Cat2: 1380, Cat1: 2400 },
  "Final":         { Cat4: 2030, Cat3: 3370, Cat2: 5040, Cat1: 6730 },
};

const tiers = (stage: Stage): PriceTier[] => [
  { category: "Cat1", label: "Category 1", description: "Premium seats — closest to halfway line", priceUsd: PRICES[stage].Cat1 },
  { category: "Cat2", label: "Category 2", description: "Lower tier, between corner flag and goal", priceUsd: PRICES[stage].Cat2 },
  { category: "Cat3", label: "Category 3", description: "Mid-tier seating, full pitch view", priceUsd: PRICES[stage].Cat3 },
  { category: "Cat4", label: "Category 4", description: "Upper tier — host-country residents pricing", priceUsd: PRICES[stage].Cat4 },
];

export const matches: Match[] = [
  {
    id: "wc26-01",
    stage: "Group Stage",
    matchNo: "Match 1",
    group: "Group A",
    date: "2026-06-11",
    kickoffLocal: "15:00",
    homeTeam: "Mexico",
    homeFlag: "🇲🇽",
    awayTeam: "South Africa",
    awayFlag: "🇿🇦",
    venue: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-02",
    stage: "Group Stage",
    matchNo: "Match 2",
    group: "Group A",
    date: "2026-06-11",
    kickoffLocal: "22:00",
    homeTeam: "South Korea",
    homeFlag: "🇰🇷",
    awayTeam: "Czechia",
    awayFlag: "🇨🇿",
    venue: "Estadio Akron",
    city: "Guadalajara",
    country: "Mexico",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-03",
    stage: "Group Stage",
    matchNo: "Match 3",
    group: "Group B",
    date: "2026-06-12",
    kickoffLocal: "15:00",
    homeTeam: "Canada",
    homeFlag: "🇨🇦",
    awayTeam: "Bosnia and Herzegovina",
    awayFlag: "🇧🇦",
    venue: "BMO Field",
    city: "Toronto",
    country: "Canada",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-04",
    stage: "Group Stage",
    matchNo: "Match 4",
    group: "Group D",
    date: "2026-06-12",
    kickoffLocal: "21:00",
    homeTeam: "USA",
    homeFlag: "🇺🇸",
    awayTeam: "Paraguay",
    awayFlag: "🇵🇾",
    venue: "SoFi Stadium",
    city: "Los Angeles",
    country: "USA",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-05",
    stage: "Group Stage",
    matchNo: "Match 5",
    group: "Group B",
    date: "2026-06-13",
    kickoffLocal: "15:00",
    homeTeam: "Qatar",
    homeFlag: "🇶🇦",
    awayTeam: "Switzerland",
    awayFlag: "🇨🇭",
    venue: "Levi's Stadium",
    city: "San Francisco Bay Area",
    country: "USA",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-06",
    stage: "Group Stage",
    matchNo: "Match 6",
    group: "Group C",
    date: "2026-06-13",
    kickoffLocal: "18:00",
    homeTeam: "Brazil",
    homeFlag: "🇧🇷",
    awayTeam: "Morocco",
    awayFlag: "🇲🇦",
    venue: "MetLife Stadium",
    city: "New York/New Jersey",
    country: "USA",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-07",
    stage: "Group Stage",
    matchNo: "Match 7",
    group: "Group C",
    date: "2026-06-13",
    kickoffLocal: "21:00",
    homeTeam: "Haiti",
    homeFlag: "🇭🇹",
    awayTeam: "Scotland",
    awayFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    venue: "Gillette Stadium",
    city: "Boston",
    country: "USA",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-08",
    stage: "Group Stage",
    matchNo: "Match 8",
    group: "Group D",
    date: "2026-06-13",
    kickoffLocal: "00:00",
    homeTeam: "Australia",
    homeFlag: "🇦🇺",
    awayTeam: "Türkiye",
    awayFlag: "🇹🇷",
    venue: "BC Place",
    city: "Vancouver",
    country: "Canada",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-09",
    stage: "Group Stage",
    matchNo: "Match 9",
    group: "Group E",
    date: "2026-06-14",
    kickoffLocal: "13:00",
    homeTeam: "Germany",
    homeFlag: "🇩🇪",
    awayTeam: "Curaçao",
    awayFlag: "🇨🇼",
    venue: "NRG Stadium",
    city: "Houston",
    country: "USA",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-10",
    stage: "Group Stage",
    matchNo: "Match 10",
    group: "Group E",
    date: "2026-06-14",
    kickoffLocal: "19:00",
    homeTeam: "Ivory Coast",
    homeFlag: "🇨🇮",
    awayTeam: "Ecuador",
    awayFlag: "🇪🇨",
    venue: "Lincoln Financial Field",
    city: "Philadelphia",
    country: "USA",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-11",
    stage: "Group Stage",
    matchNo: "Match 11",
    group: "Group F",
    date: "2026-06-14",
    kickoffLocal: "16:00",
    homeTeam: "Netherlands",
    homeFlag: "🇳🇱",
    awayTeam: "Japan",
    awayFlag: "🇯🇵",
    venue: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-12",
    stage: "Group Stage",
    matchNo: "Match 12",
    group: "Group F",
    date: "2026-06-14",
    kickoffLocal: "22:00",
    homeTeam: "Sweden",
    homeFlag: "🇸🇪",
    awayTeam: "Tunisia",
    awayFlag: "🇹🇳",
    venue: "Estadio BBVA",
    city: "Monterrey",
    country: "Mexico",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-13",
    stage: "Group Stage",
    matchNo: "Match 13",
    group: "Group G",
    date: "2026-06-15",
    kickoffLocal: "15:00",
    homeTeam: "Belgium",
    homeFlag: "🇧🇪",
    awayTeam: "Egypt",
    awayFlag: "🇪🇬",
    venue: "Lumen Field",
    city: "Seattle",
    country: "USA",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-14",
    stage: "Group Stage",
    matchNo: "Match 14",
    group: "Group G",
    date: "2026-06-15",
    kickoffLocal: "21:00",
    homeTeam: "Iran",
    homeFlag: "🇮🇷",
    awayTeam: "New Zealand",
    awayFlag: "🇳🇿",
    venue: "SoFi Stadium",
    city: "Los Angeles",
    country: "USA",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-15",
    stage: "Group Stage",
    matchNo: "Match 15",
    group: "Group H",
    date: "2026-06-15",
    kickoffLocal: "12:00",
    homeTeam: "Spain",
    homeFlag: "🇪🇸",
    awayTeam: "Cape Verde",
    awayFlag: "🇨🇻",
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-16",
    stage: "Group Stage",
    matchNo: "Match 16",
    group: "Group H",
    date: "2026-06-15",
    kickoffLocal: "18:00",
    homeTeam: "Saudi Arabia",
    homeFlag: "🇸🇦",
    awayTeam: "Uruguay",
    awayFlag: "🇺🇾",
    venue: "Hard Rock Stadium",
    city: "Miami",
    country: "USA",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-17",
    stage: "Group Stage",
    matchNo: "Match 17",
    group: "Group I",
    date: "2026-06-16",
    kickoffLocal: "15:00",
    homeTeam: "France",
    homeFlag: "🇫🇷",
    awayTeam: "Senegal",
    awayFlag: "🇸🇳",
    venue: "MetLife Stadium",
    city: "New York/New Jersey",
    country: "USA",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-18",
    stage: "Group Stage",
    matchNo: "Match 18",
    group: "Group I",
    date: "2026-06-16",
    kickoffLocal: "18:00",
    homeTeam: "Iraq",
    homeFlag: "🇮🇶",
    awayTeam: "Norway",
    awayFlag: "🇳🇴",
    venue: "Gillette Stadium",
    city: "Boston",
    country: "USA",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-19",
    stage: "Group Stage",
    matchNo: "Match 19",
    group: "Group J",
    date: "2026-06-16",
    kickoffLocal: "21:00",
    homeTeam: "Argentina",
    homeFlag: "🇦🇷",
    awayTeam: "Algeria",
    awayFlag: "🇩🇿",
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-20",
    stage: "Group Stage",
    matchNo: "Match 20",
    group: "Group J",
    date: "2026-06-17",
    kickoffLocal: "00:00",
    homeTeam: "Austria",
    homeFlag: "🇦🇹",
    awayTeam: "Jordan",
    awayFlag: "🇯🇴",
    venue: "Levi's Stadium",
    city: "San Francisco Bay Area",
    country: "USA",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-21",
    stage: "Group Stage",
    matchNo: "Match 21",
    group: "Group K",
    date: "2026-06-17",
    kickoffLocal: "13:00",
    homeTeam: "Portugal",
    homeFlag: "🇵🇹",
    awayTeam: "DR Congo",
    awayFlag: "🇨🇩",
    venue: "NRG Stadium",
    city: "Houston",
    country: "USA",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-22",
    stage: "Group Stage",
    matchNo: "Match 22",
    group: "Group K",
    date: "2026-06-17",
    kickoffLocal: "22:00",
    homeTeam: "Uzbekistan",
    homeFlag: "🇺🇿",
    awayTeam: "Colombia",
    awayFlag: "🇨🇴",
    venue: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-23",
    stage: "Group Stage",
    matchNo: "Match 23",
    group: "Group L",
    date: "2026-06-17",
    kickoffLocal: "16:00",
    homeTeam: "England",
    homeFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    awayTeam: "Croatia",
    awayFlag: "🇭🇷",
    venue: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
    prices: tiers("Group Stage"),
    featured: true,
  },
  {
    id: "wc26-24",
    stage: "Group Stage",
    matchNo: "Match 24",
    group: "Group L",
    date: "2026-06-17",
    kickoffLocal: "19:00",
    homeTeam: "Ghana",
    homeFlag: "🇬🇭",
    awayTeam: "Panama",
    awayFlag: "🇵🇦",
    venue: "BMO Field",
    city: "Toronto",
    country: "Canada",
    prices: tiers("Group Stage"),
  },
  {
    id: "wc26-r32-01",
    stage: "Round of 32",
    matchNo: "Match 73",
    date: "2026-06-28",
    kickoffLocal: "15:00",
    homeTeam: "Runner-up A",
    homeFlag: "🏆",
    awayTeam: "Runner-up B",
    awayFlag: "🏆",
    venue: "SoFi Stadium",
    city: "Los Angeles",
    country: "USA",
    prices: tiers("Round of 32"),
  },
  {
    id: "wc26-r32-02",
    stage: "Round of 32",
    matchNo: "Match 76",
    date: "2026-06-29",
    kickoffLocal: "13:00",
    homeTeam: "Winner C",
    homeFlag: "🏆",
    awayTeam: "Runner-up F",
    awayFlag: "🏆",
    venue: "NRG Stadium",
    city: "Houston",
    country: "USA",
    prices: tiers("Round of 32"),
  },
  {
    id: "wc26-r16-01",
    stage: "Round of 16",
    matchNo: "Match 89",
    date: "2026-07-04",
    kickoffLocal: "17:00",
    homeTeam: "Winner 73",
    homeFlag: "🏆",
    awayTeam: "Winner 75",
    awayFlag: "🏆",
    venue: "Lincoln Financial Field",
    city: "Philadelphia",
    country: "USA",
    prices: tiers("Round of 16"),
  },
  {
    id: "wc26-r16-02",
    stage: "Round of 16",
    matchNo: "Match 91",
    date: "2026-07-05",
    kickoffLocal: "16:00",
    homeTeam: "Winner 76",
    homeFlag: "🏆",
    awayTeam: "Winner 78",
    awayFlag: "🏆",
    venue: "MetLife Stadium",
    city: "New York/New Jersey",
    country: "USA",
    prices: tiers("Round of 16"),
  },
  {
    id: "wc26-qf-01",
    stage: "Quarter-final",
    matchNo: "Match 97",
    date: "2026-07-09",
    kickoffLocal: "16:00",
    homeTeam: "Winner 89",
    homeFlag: "🏆",
    awayTeam: "Winner 90",
    awayFlag: "🏆",
    venue: "Gillette Stadium",
    city: "Boston",
    country: "USA",
    prices: tiers("Quarter-final"),
    featured: true,
  },
  {
    id: "wc26-qf-02",
    stage: "Quarter-final",
    matchNo: "Match 98",
    date: "2026-07-10",
    kickoffLocal: "15:00",
    homeTeam: "Winner 93",
    homeFlag: "🏆",
    awayTeam: "Winner 94",
    awayFlag: "🏆",
    venue: "SoFi Stadium",
    city: "Los Angeles",
    country: "USA",
    prices: tiers("Quarter-final"),
    featured: true,
  },
  {
    id: "wc26-sf-01",
    stage: "Semi-final",
    matchNo: "Match 101",
    date: "2026-07-14",
    kickoffLocal: "15:00",
    homeTeam: "Winner 97",
    homeFlag: "🏆",
    awayTeam: "Winner 98",
    awayFlag: "🏆",
    venue: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
    prices: tiers("Semi-final"),
    featured: true,
  },
  {
    id: "wc26-sf-02",
    stage: "Semi-final",
    matchNo: "Match 102",
    date: "2026-07-15",
    kickoffLocal: "15:00",
    homeTeam: "Winner 99",
    homeFlag: "🏆",
    awayTeam: "Winner 100",
    awayFlag: "🏆",
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
    prices: tiers("Semi-final"),
    featured: true,
  },
  {
    id: "wc26-3rd",
    stage: "Third Place",
    matchNo: "Match 103",
    date: "2026-07-18",
    kickoffLocal: "17:00",
    homeTeam: "Loser 101",
    homeFlag: "🏆",
    awayTeam: "Loser 102",
    awayFlag: "🏆",
    venue: "Hard Rock Stadium",
    city: "Miami",
    country: "USA",
    prices: tiers("Third Place"),
  },
  {
    id: "wc26-final",
    stage: "Final",
    matchNo: "Match 104",
    date: "2026-07-19",
    kickoffLocal: "15:00",
    homeTeam: "Winner 101",
    homeFlag: "🏆",
    awayTeam: "Winner 102",
    awayFlag: "🏆",
    venue: "MetLife Stadium",
    city: "New York/New Jersey",
    country: "USA",
    prices: tiers("Final"),
    featured: true,
  },
];

export const getMatch = (id: string) => matches.find((m) => m.id === id);

export const formatUsd = (n: number) =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);

export const formatDate = (iso: string) =>
  new Date(iso + "T00:00:00").toLocaleDateString("en-US", {
    weekday: "short", month: "short", day: "numeric", year: "numeric",
  });
